export const myProjects = [
  {
    title: '🛡️ Kingdom Come: Deliverance',
    desc: '„Středověk bez kompromisů.“ Kingdom Come je historické RPG, které tě vrhne do realistického světa 15. století. Hraješ za Henryho, obyčejného syna kováře, který se zaplete do válečného konfliktu.',
    subdesc: 'Díky autentickému prostředí, soubojům a příběhu nabízí Kingdom Come zážitek, jaký jinde nenajdeš. Připrav se na výzvu bez magie, zato s duší české historie.',
    href: '/kcd',
    texture: '/textures/project/project1.mp4',
    logo: '/project-logo1.png',
    logoStyle: {
      backgroundColor: '#2A1816',
      border: '0.2px solid #36201D',
      boxShadow: '0px 0px 60px 0px #AA3C304D',
    },
    spotlight: '/spotlight1.png',
  },
  {
    title: '🪖 Arma Série',
    desc: '„Simulace, která definuje žánr.“ Arma je legendární vojenská simulace vytvořená českým studiem Bohemia Interactive. Nabízí obří mapy, taktiku a realistické bojiště.',
    subdesc: 'S podporou modů a komunitních misí se Arma stala základem herního sandboxu pro fanoušky armádních scénářů po celém světě.',
    href: '/arma',
    texture: '/textures/project/project2.mp4',
    logo: '/project-logo2.png',
    logoStyle: {
      backgroundColor: '#13202F',
      border: '0.2px solid #17293E',
      boxShadow: '0px 0px 60px 0px #2F6DB54D',
    },
    spotlight: '/spotlight2.png',
  },
  {
    title: '🔫 Mafia Série',
    desc: '„Gangsterská legenda začíná tady.“ Vžij se do role Tommyho Angela v městě Lost Heaven během 30. let. Mafia nabízí filmový příběh, silnou atmosféru a ikonická auta.',
    subdesc: 'Tento český klenot ukázal světu, že herní příběh může být stejně silný jako ten filmový. Čas se vrátit do zlaté éry zločinu.',
    href: '/mafia',
    texture: '/textures/project/project3.mp4',
    logo: '/project-logo3.png',
    logoStyle: {
      backgroundColor: '#60f5a1',
      background:
        'linear-gradient(0deg, #60F5A150, #60F5A150), linear-gradient(180deg, rgba(255, 255, 255, 0.9) 0%, rgba(208, 213, 221, 0.8) 100%)',
      border: '0.2px solid rgba(208, 213, 221, 1)',
      boxShadow: '0px 0px 60px 0px rgba(35, 131, 96, 0.3)',
    },
    spotlight: '/spotlight3.png',
  },
  {
    title: '🚛 Euro Truck Simulator 1–2',
    desc: '„Cesta je cíl.“ Euro Truck je zážitek, který proměnil řízení kamionu v relaxační fenomén. Vyvíjeno českým studiem SCS Software, hra nabízí stovky měst a tisíce kilometrů silnic.',
    subdesc: 'Vytvoř si vlastní dopravní firmu a poznávej Evropu po své ose. Hra, která je o cestě – ne jen o cíli.',
    href: '/eurotruck',
    texture: '/textures/project/project4.mp4',
    logo: '/project-logo4.png',
    logoStyle: {
      backgroundColor: '#0E1F38',
      border: '0.2px solid #0E2D58',
      boxShadow: '0px 0px 60px 0px #2F67B64D',
    },
    spotlight: '/spotlight4.png',
  },
];
